import { adapterManifest } from "./adapters/registry.js";
import { merchantProfiles } from "./merchants/profiles.js";
import type { AgentShackListing } from "./types.js";

function agentShackListing(origin: string): AgentShackListing {
  return {
    id: "sllr-merchant-order-agent",
    name: "SLL-R",
    type: "merchant_agent",
    category: "local_commerce",
    version: "0.1.0",
    modes: ["one_time_call", "subscription", "fork"],
    runtime: {
      type: "hosted_endpoint",
      manifestUrl: `${origin}/.well-known/sllr-agent.json`,
    },
    evaluator: {
      policy: "order-fulfillment-v0",
      checks: [
        "merchant accepted or rejected the order",
        "merchant marked fulfillment or payment proof was attached",
        "receipt handoff includes order, merchant, item, status, and receipt hash",
      ],
    },
    receipt: {
      requiredFields: [
        "receiptId",
        "agentId",
        "workflowId",
        "operatorId",
        "merchantId",
        "customerId",
        "serviceType",
        "requestHash",
        "status",
        "evaluatorPolicyId",
        "evaluatorVerdict",
        "proofLevel",
        "receiptHash",
        "createdAt",
      ],
      proofLevels: ["order_intent_only", "payment_backed", "fulfilled", "receipt_memory_issued"],
    },
    settlement: {
      pass: "release_or_mark_completed",
      fail: "refund_revision_or_dispute",
    },
    reputation: {
      subjects: ["merchant", "customer", "agent", "evaluator"],
    },
    forking: {
      allowed: true,
      forkable: ["catalog", "merchant_profile", "staff_terminal", "checkout_adapter", "receipt_policy"],
      lineageFeeBps: 0,
    },
  };
}

export function sllrManifest(origin: string) {
  return {
    name: "SLL-R",
    description: "Installable seller agents for merchants in the agent economy.",
    version: "0.1.0",
    role: "seller_operating_agent",
    agentShack: agentShackListing(origin),
    dojo: {
      listingName: "SLL-R",
      category: "merchant agent",
      installModes: ["hosted", "template", "self-hosted"],
      buyerAgents: ["BUY-R", "Hermes", "ChatGPT", "Dojo workflows"],
    },
    boundaries: {
      sllr: "seller agent runtime",
      receiptMemory: "proof and receipt memory system",
      posAdapters: "internal checkout and POS workflow tools used by SLL-R",
    },
    endpoints: {
      manifest: `${origin}/.well-known/sllr-agent.json`,
      mcpManifest: `${origin}/.well-known/sllr-mcp.json`,
      aiPluginManifest: `${origin}/.well-known/ai-plugin.json`,
      baseMcpPluginSpec: `${origin}/.well-known/base-mcp-plugin.md`,
      solanaPluginSpec: `${origin}/.well-known/solana-sllr-plugin.md`,
      openapi: `${origin}/openapi.json`,
      capabilities: `${origin}/capabilities`,
      standaloneAgent: `${origin}/agent/{merchantId}`,
      standaloneAgentMessage: `${origin}/agent/{merchantId}/message`,
      merchantTerminal: `${origin}/terminal/{merchantId}`,
      merchants: `${origin}/merchants`,
      merchantMenu: `${origin}/merchants/{merchantId}/menu`,
      merchantQuote: `${origin}/merchants/{merchantId}/quote`,
      merchantOrders: `${origin}/merchants/{merchantId}/orders`,
      merchantPaymentOptions: `${origin}/merchants/{merchantId}/payment-options`,
      merchantPayment: `${origin}/merchants/{merchantId}/payment`,
      merchantReceipt: `${origin}/merchants/{merchantId}/receipt`,
      shopifyMerchants: `${origin}/shopify/merchants`,
      shopifyConnect: `${origin}/shopify/merchants/{merchantId}/connect`,
      shopifyProducts: `${origin}/shopify/merchants/{merchantId}/products`,
      shopifyCart: `${origin}/shopify/merchants/{merchantId}/cart`,
      shopifyOrdersPaidWebhook: `${origin}/webhooks/shopify/orders-paid`,
      shopifyOrdersFulfilledWebhook: `${origin}/webhooks/shopify/orders-fulfilled`,
      quote: `${origin}/quote`,
      orders: `${origin}/orders`,
      paymentWebhook: `${origin}/webhooks/payment`,
      solanaPayMerchants: `${origin}/solana-pay/merchants`,
      solanaPayPreparePayment: `${origin}/solana-pay/prepare-payment`,
      solanaPayVerifyPayment: `${origin}/solana-pay/verify-payment`,
      helioWebhook: `${origin}/webhooks/helio`,
    },
    capabilities: [
      "merchant catalog discovery",
      "hosted customer ordering agent",
      "hosted merchant terminal",
      "pickup promise management",
      "quote-first order negotiation",
      "checkout handoff",
      "payment proof intake",
      "SLL-R receipt memory handoff",
      "Solana receipt cNFT ready proof",
      "OpenAPI tool discovery",
      "generic merchant MCP tool discovery",
      "Base MCP custom plugin instructions",
      "Solana Pay merchant plugin instructions",
      "Shopify Storefront MCP connect plan",
      "Shopify paid order webhook proof",
    ],
    tools: [
      {
        name: "open_standalone_agent",
        method: "GET",
        path: "/agent/{merchantId}",
        description: "Open the hosted SLL-R customer ordering agent for a merchant.",
      },
      {
        name: "message_standalone_agent",
        method: "POST",
        path: "/agent/{merchantId}/message",
        description: "Quote or create an order from customer natural-language intent.",
      },
      {
        name: "open_merchant_terminal",
        method: "GET",
        path: "/terminal/{merchantId}",
        description: "Open the hosted SLL-R merchant order terminal.",
      },
      {
        name: "list_merchants",
        method: "GET",
        path: "/merchants",
        description: "List configured merchants an agent can quote or order from.",
      },
      {
        name: "get_merchant_menu",
        method: "GET",
        path: "/merchants/{merchantId}/menu",
        description: "Fetch catalog and menu sections for a merchant.",
      },
      {
        name: "quote_merchant_order",
        method: "POST",
        path: "/merchants/{merchantId}/quote",
        description: "Return feasibility, item match, price, ETA, and alternatives for buyer intent.",
      },
      {
        name: "create_merchant_order",
        method: "POST",
        path: "/merchants/{merchantId}/orders",
        description: "Create an order after quote acceptance.",
      },
      {
        name: "prepare_merchant_payment_options",
        method: "POST",
        path: "/merchants/{merchantId}/payment-options",
        description: "Return normal checkout and web3 payment options for an order.",
      },
      {
        name: "prepare_base_coffee_payment",
        method: "GET",
        path: "/base-plugin/coffee/prepare-payment",
        description: "Return Base USDC calldata that maps to Base MCP send_calls.",
      },
      {
        name: "record_base_coffee_demo_payment",
        method: "GET",
        path: "/base-plugin/coffee/record-demo-payment",
        description: "Record Base MCP request or transaction id and issue demo receipt memory.",
      },
      {
        name: "prepare_solana_payment",
        method: "GET",
        path: "/solana-pay/prepare-payment",
        description: "Return Solana Pay URL or Helio checkout handoff for Solana rail merchants.",
      },
      {
        name: "verify_solana_payment",
        method: "POST",
        path: "/solana-pay/verify-payment",
        description: "Attach Solana Pay or Helio proof after reference and verifier checks.",
      },
      {
        name: "list_shopify_merchants",
        method: "GET",
        path: "/shopify/merchants",
        description: "List Shopify-capable merchants and their Storefront MCP / webhook setup paths.",
      },
      {
        name: "create_shopify_cart_handoff",
        method: "POST",
        path: "/shopify/merchants/{merchantId}/cart",
        description: "Return Shopify checkout handoff and metadata needed to bind the paid order to SLL-R receipt memory.",
      },
    ],
    adapters: adapterManifest(),
    exampleMerchants: Object.values(merchantProfiles).map((merchant) => ({
      id: merchant.id,
      name: merchant.name,
      fulfillment: merchant.fulfillment,
      paymentRails: merchant.paymentRails,
    })),
  };
}
