export function sllrMcpManifest(origin: string) {
  return {
    name: "SLL-R Merchant MCP",
    version: "0.1.0",
    description: "Merchant-backed commerce tools for personal-agent comparison, quote, consent, order, payment options, fulfillment status, and receipt memory.",
    transport: {
      type: "streamable_http",
      url: `${origin}/mcp`,
      baseUrl: origin,
      note: "POST JSON-RPC MCP messages to /mcp. The REST paths below are the equivalent OpenAPI surface for non-MCP agents.",
    },
    safety: {
      paymentApproval: "Always show payment rail, merchant, amount, recipient or checkout URL, and proof requirements before asking the user to approve payment.",
      noAutonomousPayment: true,
      proofBeforeReceipt: "Final receipt memory requires merchant fulfillment or customer claim. Payment proof alone only moves the order to payment_backed.",
    },
    tools: [
      {
        name: "list_merchants",
        method: "GET",
        path: "/merchants",
        description: "List merchants that SLL-R can quote and order from.",
      },
      {
        name: "get_merchant",
        method: "GET",
        path: "/merchants/{merchantId}",
        description: "Read merchant profile, fulfillment modes, and supported payment rails.",
      },
      {
        name: "get_menu",
        method: "GET",
        path: "/merchants/{merchantId}/menu",
        description: "Read normalized catalog and menu sections for a merchant.",
      },
      {
        name: "list_offers",
        method: "GET",
        path: "/merchants/{merchantId}/offers",
        description: "List Level 1 fixed merchant-backed offers that can enter the normal quote and consent flow.",
      },
      {
        name: "quote_offer",
        method: "POST",
        path: "/merchants/{merchantId}/offers/{offerId}/quote",
        description: "Quote one exact Level 1 offer, optionally against a requested pickup time.",
      },
      {
        name: "list_capacity_windows",
        method: "GET",
        path: "/merchants/{merchantId}/capacity",
        description: "Read Level 3 pickup capacity by 15-minute production window. Availability is held only by buyer-authenticated, consent-bound order creation.",
      },
      {
        name: "shop_for_me",
        method: "POST",
        path: "/buyer/shop",
        description: "Compare bounded merchant candidates and return ranked, persisted merchant-backed quotes. Requires a buyer bearer token and never creates an order or payment.",
        inputSchema: {
          type: "object",
          required: ["userIntent"],
          properties: {
            userIntent: { type: "string" },
            maxSpendUsd: { type: "string" },
            deadlineMinutes: { type: "number" },
            deliverByDays: { type: "number" },
            quantity: { type: "number" },
            offerId: { type: "string" },
            pickupAt: { type: "string", format: "date-time" },
            merchantIds: { type: "array", maxItems: 8, uniqueItems: true, items: { type: "string" } },
            category: { type: "string" },
            lat: { type: "number" },
            lng: { type: "number" },
            radiusKm: { type: "number" },
            limit: { type: "number", maximum: 5 },
          },
        },
      },
      {
        name: "quote_order",
        method: "POST",
        path: "/merchants/{merchantId}/quote",
        description: "Quote buyer intent against merchant catalog, budget, quantity, pickup deadline, or shipping deadline.",
        inputSchema: {
          type: "object",
          required: ["userIntent"],
          properties: {
            userIntent: { type: "string" },
            itemId: { type: "string" },
            maxSpendUsd: { type: "string" },
            deadlineMinutes: { type: "number" },
            deliverByDays: { type: "number" },
            quantity: { type: "number" },
          },
        },
      },
      {
        name: "request_consent",
        method: "POST",
        path: "/consent",
        description: "Bind explicit buyer confirmation to a live quote before an authenticated order mutation.",
        inputSchema: {
          type: "object",
          required: ["quoteId", "confirmationText"],
          properties: {
            quoteId: { type: "string" },
            confirmationText: { type: "string" },
          },
        },
      },
      {
        name: "create_order",
        method: "POST",
        path: "/merchants/{merchantId}/orders",
        description: "Create an SLL-R order after the quote is acceptable to the user.",
        inputSchema: {
          type: "object",
          required: ["userIntent"],
          properties: {
            userIntent: { type: "string" },
            itemId: { type: "string" },
            quoteId: { type: "string" },
            consentId: { type: "string" },
            maxSpendUsd: { type: "string" },
            deadlineMinutes: { type: "number" },
            deliverByDays: { type: "number" },
            quantity: { type: "number" },
            agentId: { type: "string" },
            customerLabel: { type: "string" },
            paymentMode: { type: "string", enum: ["counter", "checkout", "crypto"] },
            offerId: { type: "string" },
            pickupAt: { type: "string", format: "date-time" },
          },
        },
      },
      {
        name: "list_orders",
        method: "GET",
        path: "/merchants/{merchantId}/orders",
        description: "List SLL-R orders for a merchant, optionally filtered by status.",
      },
      {
        name: "create_fulfillment_batch",
        method: "POST",
        path: "/merchants/{merchantId}/batches",
        description: "Group independently paid, same-window orders into one Level 2 merchant fulfillment batch. Each child retains its own consent, payment, and receipt identity.",
      },
      {
        name: "list_fulfillment_batches",
        method: "GET",
        path: "/merchants/{merchantId}/batches",
        description: "List Level 2 fulfillment batches for an authorized merchant operator.",
      },
      {
        name: "get_fulfillment_batch",
        method: "GET",
        path: "/merchants/{merchantId}/batches/{batchId}",
        description: "Read one Level 2 batch and its independently settled child orders.",
      },
      {
        name: "get_payment_options",
        method: "POST",
        path: "/merchants/{merchantId}/payment-options",
        description: "List payment options for an existing order across the merchant's enabled rails: counter, Shopify checkout, Base USDC, Solana Pay, Helio.",
        inputSchema: {
          type: "object",
          required: ["orderId"],
          properties: {
            orderId: { type: "string" },
            payer: { type: "string" },
          },
        },
      },
      {
        name: "attach_payment_proof",
        method: "POST",
        path: "/merchants/{merchantId}/payment",
        description: "Attach verified or demo payment proof to an order. This never proves fulfillment or issues final receipt memory.",
      },
      {
        name: "issue_receipt",
        method: "POST",
        path: "/merchants/{merchantId}/receipt",
        description: "Record merchant fulfillment and issue final receipt memory. Requires the merchant verifier secret (x-sllr-merchant-payment-secret header or verificationToken); demo=true is only accepted when no secret is configured.",
      },
      {
        name: "check_order_status",
        method: "GET",
        path: "/orders/{orderId}",
        description: "Read current order state, payment status, fulfillment state, and receipt handoff.",
      },
      {
        name: "list_my_orders",
        method: "GET",
        path: "/buyer/orders",
        description: "List the calling buyer's own orders across all merchants. Requires an Authorization: Bearer <buyer token> from POST /buyer/session.",
      },
      {
        name: "create_demo_merchant",
        method: "POST",
        path: "/demo-merchants",
        description: "Ingest a public Shopify storefront's products.json into a runtime demo merchant with counter + Shopify checkout rails.",
        inputSchema: {
          type: "object",
          required: ["storeDomain"],
          properties: {
            storeDomain: { type: "string" },
            name: { type: "string" },
            category: { type: "string" },
            location: { type: "string" },
            fulfillment: { type: "string", enum: ["pickup", "shipping", "both"] },
          },
        },
      },
    ],
    adapters: {
      normalCheckout: ["shopify", "stripe", "counter"],
      web3: ["base_usdc", "solana_pay", "helio", "moonpay", "binance_pay"],
      staff: ["merchant_terminal", "telegram_staff"],
    },
    exampleMerchants: [
      "raposa-coffee",
      "raposa-shop",
      "solyd",
      "noun-coffee",
    ],
    docs: `${origin}/docs/sllr-mcp-runbook.md`,
    openapi: `${origin}/openapi.json`,
  };
}
